/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as LayoutImport } from './routes/_layout';
import { Route as LayoutAuthImport } from './routes/_layout/_auth';
import { Route as LayoutAboutIndexImport } from './routes/_layout/about/index';
import { Route as IndexImport } from './routes/index';

// Create Virtual Routes

const LayoutAuthSignupIndexLazyImport = createFileRoute('/_layout/_auth/signup/')();
const LayoutAuthLoginIndexLazyImport = createFileRoute('/_layout/_auth/login/')();

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutAboutIndexRoute = LayoutAboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutAuthSignupIndexLazyRoute = LayoutAuthSignupIndexLazyImport.update({
  path: '/signup/',
  getParentRoute: () => LayoutAuthRoute,
} as any).lazy(() => import('./routes/_layout/_auth/signup/index.lazy').then(d => d.Route));

const LayoutAuthLoginIndexLazyRoute = LayoutAuthLoginIndexLazyImport.update({
  path: '/login/',
  getParentRoute: () => LayoutAuthRoute,
} as any).lazy(() => import('./routes/_layout/_auth/login/index.lazy').then(d => d.Route));

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout/_auth': {
      id: '/_layout/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutAuthImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/about/': {
      id: '/_layout/about/';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof LayoutAboutIndexImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/_auth/login/': {
      id: '/_layout/_auth/login/';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LayoutAuthLoginIndexLazyImport;
      parentRoute: typeof LayoutAuthImport;
    };
    '/_layout/_auth/signup/': {
      id: '/_layout/_auth/signup/';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof LayoutAuthSignupIndexLazyImport;
      parentRoute: typeof LayoutAuthImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutAuthRoute: LayoutAuthRoute.addChildren({
      LayoutAuthLoginIndexLazyRoute,
      LayoutAuthSignupIndexLazyRoute,
    }),
    LayoutAboutIndexRoute,
  }),
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/about/"
      ]
    },
    "/_layout/_auth": {
      "filePath": "_layout/_auth.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_auth/login/",
        "/_layout/_auth/signup/"
      ]
    },
    "/_layout/about/": {
      "filePath": "_layout/about/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_auth/login/": {
      "filePath": "_layout/_auth/login/index.lazy.tsx",
      "parent": "/_layout/_auth"
    },
    "/_layout/_auth/signup/": {
      "filePath": "_layout/_auth/signup/index.lazy.tsx",
      "parent": "/_layout/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
