image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    init: |
      dotnet tool restore
      dotnet dev-certs https
      pnpm install
      gp sync-done install
  - name: API
    init: gp sync-await install
    command: |
      gp ports await 5432
      nx serve api
  - name: Web
    init: gp sync-await install
    command: nx serve web
  - name: Toolkit
    init: gp sync-await install
    command: nx run toolkit:storybook
  - name: Getting Started
    command: |
      echo Your environment is starting soon...
      echo You can view the other terminals to see the progress.
      echo [API URL - HTTP]: "$(gp url 5000)"
      echo [API URL - HTTPS]: "$(gp url 5001)"
      echo [Web URL]: "$(gp url 3000)"
      echo [Toolkit URL]: "$(gp url 4400)"

ports:
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: ignore
  - name: API (HTTP)
    description: The main API server (HTTP)
    port: 5000
    onOpen: ignore
  - name: API (HTTPS)
    description: The main API server (HTTPS)
    port: 5001
    onOpen: ignore
  - name: Database
    description: The PostgreSQL database instance
    port: 5432
    onOpen: ignore
  - name: NX Graph
    description: The NX dependency graph server
    port: 4211
    onOpen: ignore
  - name: Toolkit
    description: The Storybook server
    port: 4400
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - muhammad-sammy.csharp
    - ms-dotnettools.vscode-dotnet-runtime
    - graphql.vscode-graphql-syntax
    - EditorConfig.EditorConfig
