image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    init: |
      dotnet dev-certs https
      pnpm install
      gp sync-done install
  # - name: Run
  #   init: gp sync-await install
  #   command: |
  #     # Wait until PostgreSQL is reachable
  #     until mysqladmin ping; do
  #         sleep 1
  #     done

  #     nx serve web
  #     nx serve api

  #     echo 'Your environment is now ready!'
  #     echo '[API URL]: HTTP - $(gp url 5000); HTTPS - $(gp url 5001)'
  #     echo '[Web URL]: $(gp url 3000)'

ports:
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: open-browser
  - name: API (HTTP)
    description: The main API server (HTTP)
    port: 5000
    onOpen: ignore
  - name: API (HTTPS)
    description: The main API server (HTTPS)
    port: 5001
    onOpen: ignore
  - name: Database
    description: The PostgreSQL database instance
    port: 5432
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
