/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutProtectedImport } from './routes/_layout/_protected'
import { Route as LayoutAuthImport } from './routes/_layout/_auth'

// Create Virtual Routes

const LayoutProtectedClubsIndexLazyImport = createFileRoute(
  '/_layout/_protected/clubs/',
)()
const LayoutAuthSignupIndexLazyImport = createFileRoute(
  '/_layout/_auth/signup/',
)()
const LayoutAuthLoginIndexLazyImport = createFileRoute(
  '/_layout/_auth/login/',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProtectedRoute = LayoutProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProtectedClubsIndexLazyRoute =
  LayoutProtectedClubsIndexLazyImport.update({
    path: '/clubs/',
    getParentRoute: () => LayoutProtectedRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_protected/clubs/index.lazy').then((d) => d.Route),
  )

const LayoutAuthSignupIndexLazyRoute = LayoutAuthSignupIndexLazyImport.update({
  path: '/signup/',
  getParentRoute: () => LayoutAuthRoute,
} as any).lazy(() =>
  import('./routes/_layout/_auth/signup/index.lazy').then((d) => d.Route),
)

const LayoutAuthLoginIndexLazyRoute = LayoutAuthLoginIndexLazyImport.update({
  path: '/login/',
  getParentRoute: () => LayoutAuthRoute,
} as any).lazy(() =>
  import('./routes/_layout/_auth/login/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutProtectedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/login/': {
      id: '/_layout/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutAuthLoginIndexLazyImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/signup/': {
      id: '/_layout/_auth/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutAuthSignupIndexLazyImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_protected/clubs/': {
      id: '/_layout/_protected/clubs/'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof LayoutProtectedClubsIndexLazyImport
      parentRoute: typeof LayoutProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutAuthRoute: LayoutAuthRoute.addChildren({
      LayoutAuthLoginIndexLazyRoute,
      LayoutAuthSignupIndexLazyRoute,
    }),
    LayoutProtectedRoute: LayoutProtectedRoute.addChildren({
      LayoutProtectedClubsIndexLazyRoute,
    }),
    LayoutIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/_protected",
        "/_layout/"
      ]
    },
    "/_layout/_auth": {
      "filePath": "_layout/_auth.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_auth/login/",
        "/_layout/_auth/signup/"
      ]
    },
    "/_layout/_protected": {
      "filePath": "_layout/_protected.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_protected/clubs/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_auth/login/": {
      "filePath": "_layout/_auth/login/index.lazy.tsx",
      "parent": "/_layout/_auth"
    },
    "/_layout/_auth/signup/": {
      "filePath": "_layout/_auth/signup/index.lazy.tsx",
      "parent": "/_layout/_auth"
    },
    "/_layout/_protected/clubs/": {
      "filePath": "_layout/_protected/clubs/index.lazy.tsx",
      "parent": "/_layout/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
