global using System.Reflection;
global using Api.Data;
global using Api.Data.Entities;
global using Api.Types;
global using HotChocolate.AspNetCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
