name: Code Quality Check

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        name: Derive appropriate SHAs for base and head for `nx affected` commands

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        with:
          version: 8.6.3

      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version: '18'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm affected:tsc -- -parallel --max-parallel=3
      - run: pnpm affected:lint -- -parallel --max-parallel=3
      # - run: pnpm exec nx affected --target=test --parallel --max-parallel=2
      # - run: pnpm exec nx affected --target=build --parallel --max-parallel=3
